version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-laravel
    container_name: app
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/laravel
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/laravel
    networks:
      - app-network

  #MySQL Service
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql
    tty: true
    ports:
      - 3306:3306
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge